//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weverca.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MetricsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MetricsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Weverca.Web.Properties.MetricsResources", typeof(MetricsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __autoload redeclaration presence or spl_autoload_register call: {0}.
        /// </summary>
        internal static string Autoload {
            get {
                return ResourceManager.GetString("Autoload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class alias construction presence: {0}.
        /// </summary>
        internal static string ClassAlias {
            get {
                return ResourceManager.GetString("ClassAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class coupling: {0}.
        /// </summary>
        internal static string ClassCoupling {
            get {
                return ResourceManager.GetString("ClassCoupling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class construct presence: {0}.
        /// </summary>
        internal static string ClassOrInterface {
            get {
                return ResourceManager.GetString("ClassOrInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyclomatic complexity: {0}.
        /// </summary>
        internal static string Cyclomacity {
            get {
                return ResourceManager.GetString("Cyclomacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duck Typing presence: {0}.
        /// </summary>
        internal static string DuckTyping {
            get {
                return ResourceManager.GetString("DuckTyping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic call presence: {0}.
        /// </summary>
        internal static string DynamicCall {
            get {
                return ResourceManager.GetString("DynamicCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic dereference presence: {0}.
        /// </summary>
        internal static string DynamicDereference {
            get {
                return ResourceManager.GetString("DynamicDereference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include based on dynamic variable presence: {0}.
        /// </summary>
        internal static string DynamicInclude {
            get {
                return ResourceManager.GetString("DynamicInclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eval function usage: {0}.
        /// </summary>
        internal static string Eval {
            get {
                return ResourceManager.GetString("Eval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declaration of class/function inside another function presence: {0}.
        /// </summary>
        internal static string InsideFunctionDeclaration {
            get {
                return ResourceManager.GetString("InsideFunctionDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magic function presence: {0}.
        /// </summary>
        internal static string MagicMethods {
            get {
                return ResourceManager.GetString("MagicMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum inheritance depth: {0}.
        /// </summary>
        internal static string MaxInheritanceDepth {
            get {
                return ResourceManager.GetString("MaxInheritanceDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum method overriding depth: {0}.
        /// </summary>
        internal static string MaxMethodOverridingDepth {
            get {
                return ResourceManager.GetString("MaxMethodOverridingDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My SQL functions presence: {0}.
        /// </summary>
        internal static string MySql {
            get {
                return ResourceManager.GetString("MySql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of lines: {0}.
        /// </summary>
        internal static string NumberOfLines {
            get {
                return ResourceManager.GetString("NumberOfLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of sources: {0}.
        /// </summary>
        internal static string NumberOfSources {
            get {
                return ResourceManager.GetString("NumberOfSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passing variable by reference at call side: {0}.
        /// </summary>
        internal static string PassingByReferenceAtCallSide {
            get {
                return ResourceManager.GetString("PassingByReferenceAtCallSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP standard functions coupling: {0}.
        /// </summary>
        internal static string PhpFunctionsCoupling {
            get {
                return ResourceManager.GetString("PhpFunctionsCoupling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias presence: {0}.
        /// </summary>
        internal static string References {
            get {
                return ResourceManager.GetString("References", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session usage: {0}.
        /// </summary>
        internal static string Session {
            get {
                return ResourceManager.GetString("Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super global variable usage: {0}.
        /// </summary>
        internal static string SuperGlobalVariable {
            get {
                return ResourceManager.GetString("SuperGlobalVariable", resourceCulture);
            }
        }
    }
}
