//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weverca.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Weverca.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?
        ///
        ///
        ///for ($x = 1, $y = 1; $x &lt; 10 &amp;&amp; $y &lt; 5; $x++, $y++)
        ///{
        ///  $b = $x * $y;
        ///  
        ///  if ($x == $y)
        ///  {
        ///    for ($i = 1; $i &lt; foo(); $i--)
        ///    {
        ///      $f = 3;
        ///    }
        ///  }
        ///
        ///  $a = $x + $y;
        ///}
        ///
        ///for ($x = 1, $y = 1; $x &lt; 10 || $y &lt; 5; $x++, $y++)
        ///{
        ///  $a = $x + $y;
        ///}
        ///
        ///for ($x = 1, $y = 1; $x &lt; 10, $y &lt; 5; $x++, $y++)
        ///{
        ///  $a = $x + $y;
        ///}
        ///
        ///
        ///$end = 1;
        ///
        ///
        ///
        ///?&gt;.
        /// </summary>
        public static string Input1 {
            get {
                return ResourceManager.GetString("Input1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?
        ///function a(){
        ///echo &quot;function a&quot;;
        ///}
        ///class b{
        ///
        ///function toString(){
        ///
        ///}
        ///
        ///}
        /////coment
        ///do{
        ///	$a=$a+$a;
        ///	echo &quot;cycle&quot;;
        ///	do
        ///	{
        ///		$a=$a*$a;
        ///		echo &quot;inner cycle&quot;;
        ///	}while(&quot;true&quot;==&quot;true&quot;);
        ///	$a=8;
        ///	echo &quot;cycle&quot;;
        ///}while(&quot;true&quot;==&quot;true&quot;);
        ///echo &quot;end&quot;;
        ///
        ///
        ///?&gt;.
        /// </summary>
        public static string Input2 {
            get {
                return ResourceManager.GetString("Input2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string InputType {
            get {
                return ResourceManager.GetString("InputType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Php Code.
        /// </summary>
        public static string PhpCode {
            get {
                return ResourceManager.GetString("PhpCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        public static string Validate {
            get {
                return ResourceManager.GetString("Validate", resourceCulture);
            }
        }
    }
}
