//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weverca.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Weverca.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are sorry, but the analysis over your source code timeouted..
        /// </summary>
        public static string AnalysisTimeouted {
            get {
                return ResourceManager.GetString("AnalysisTimeouted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:### ### ##0.##}.
        /// </summary>
        public static string DoubleFormat {
            get {
                return ResourceManager.GetString("DoubleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP Code verification.
        /// </summary>
        public static string IndexTitle {
            get {
                return ResourceManager.GetString("IndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicator Metrics.
        /// </summary>
        public static string IndicatorMetrics {
            get {
                return ResourceManager.GetString("IndicatorMetrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello
        ///
        ///&lt;?php	
        ///	function printName($name){
        ///		echo $name;
        ///	}
        ///
        ///
        ///	$name=$_POST[&quot;name&quot;];
        ///	printName($name);
        ///	
        ///?&gt;.
        /// </summary>
        public static string Input1 {
            get {
                return ResourceManager.GetString("Input1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input 1.
        /// </summary>
        public static string Input1Description {
            get {
                return ResourceManager.GetString("Input1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?
        ///function a(){
        ///echo &quot;function a&quot;;
        ///}
        ///class b{
        ///
        ///function toString(){
        ///
        ///}
        ///
        ///}
        /////coment
        ///do{
        ///	$a=$a+$a;
        ///	echo &quot;cycle&quot;;
        ///	do
        ///	{
        ///		$a=$a*$a;
        ///		echo &quot;inner cycle&quot;;
        ///	}while(&quot;true&quot;==&quot;true&quot;);
        ///	$a=8;
        ///	echo &quot;cycle&quot;;
        ///}while(&quot;true&quot;==&quot;true&quot;);
        ///echo &quot;end&quot;;
        ///
        ///
        ///?&gt;.
        /// </summary>
        public static string Input2 {
            get {
                return ResourceManager.GetString("Input2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input 2.
        /// </summary>
        public static string Input2Description {
            get {
                return ResourceManager.GetString("Input2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Input.
        /// </summary>
        public static string InputCustomDescription {
            get {
                return ResourceManager.GetString("InputCustomDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string InputType {
            get {
                return ResourceManager.GetString("InputType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:### ### ##0}.
        /// </summary>
        public static string IntegerFormat {
            get {
                return ResourceManager.GetString("IntegerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metrics Results.
        /// </summary>
        public static string MetricsResults {
            get {
                return ResourceManager.GetString("MetricsResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Warnings.
        /// </summary>
        public static string OtherWarnings {
            get {
                return ResourceManager.GetString("OtherWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Php Code.
        /// </summary>
        public static string PhpCode {
            get {
                return ResourceManager.GetString("PhpCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Metrics.
        /// </summary>
        public static string QuantityMetrics {
            get {
                return ResourceManager.GetString("QuantityMetrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating Metrics.
        /// </summary>
        public static string RatingMetrics {
            get {
                return ResourceManager.GetString("RatingMetrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification results.
        /// </summary>
        public static string ResultTitle {
            get {
                return ResourceManager.GetString("ResultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run metrics indicating construct presence.
        /// </summary>
        public static string RunIndicatorMetrics {
            get {
                return ResourceManager.GetString("RunIndicatorMetrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run metrics measuring quantity of constructs in the code.
        /// </summary>
        public static string RunQuantityMetrics {
            get {
                return ResourceManager.GetString("RunQuantityMetrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run metrics rating the code.
        /// </summary>
        public static string RunRatingMetrics {
            get {
                return ResourceManager.GetString("RunRatingMetrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run verification.
        /// </summary>
        public static string RunVerification {
            get {
                return ResourceManager.GetString("RunVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Warnings.
        /// </summary>
        public static string SecurityWarnings {
            get {
                return ResourceManager.GetString("SecurityWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifications Results.
        /// </summary>
        public static string VerificationResults {
            get {
                return ResourceManager.GetString("VerificationResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string Verify {
            get {
                return ResourceManager.GetString("Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnings.
        /// </summary>
        public static string Warnings {
            get {
                return ResourceManager.GetString("Warnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
