//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weverca.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Weverca.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    Weverca web is a simple user-friendly GUI for Weverca tool, which can be used as an alternative to Weverca console application.
        ///    It is written in ASP.NET MVC 4 under .NET framework 4.5. Framework version is required because Weverca is written in mentioned version.
        ///    It is not needed for the web interface itself.
        ///&lt;/p&gt;
        ///
        ///&lt;p&gt;
        ///    The user interface consists of a PHP code editor, checkboxes which tells the framework if we want to run verification and what metrics we want to run.
        ///    After th [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutContent {
            get {
                return ResourceManager.GetString("AboutContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are sorry, but the analysis over your source code timeouted..
        /// </summary>
        public static string AnalysisTimeouted {
            get {
                return ResourceManager.GetString("AnalysisTimeouted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:### ### ##0.##}.
        /// </summary>
        public static string DoubleFormat {
            get {
                return ResourceManager.GetString("DoubleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endless loop.
        /// </summary>
        public static string EndlessLoop {
            get {
                return ResourceManager.GetString("EndlessLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?
        ///// zabranime cashovani
        ///header(&apos;Cache-Control: no-cache&apos;);
        ///header(&apos;Pragma: no-cache&apos;);
        ///header(&apos;Content-type: image/png&apos;); 
        ///
        ///  $re_st = -2;                                                         //Pozice začátku imaginární části
        ///  $im_st = 1.2;                                                          //Pozice začátku reálné části
        ///  $incr = 0.005;                                                           //Měřítko přírustku - 1px = 1 / 20
        ///  $max_iter = 100;                                          [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Fractal {
            get {
                return ResourceManager.GetString("Fractal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fractal.
        /// </summary>
        public static string FractalDescription {
            get {
                return ResourceManager.GetString("FractalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP Code verification.
        /// </summary>
        public static string IndexTitle {
            get {
                return ResourceManager.GetString("IndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicator Metrics.
        /// </summary>
        public static string IndicatorMetrics {
            get {
                return ResourceManager.GetString("IndicatorMetrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello
        ///
        ///&lt;?php	
        ///	function printName($name){
        ///		echo $name;
        ///	}
        ///
        ///
        ///	$name=$_POST[&quot;name&quot;];
        ///	printName($name);
        ///	
        ///?&gt;.
        /// </summary>
        public static string Input1 {
            get {
                return ResourceManager.GetString("Input1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?
        ///function a(){
        ///echo &quot;function a&quot;;
        ///}
        ///class b{
        ///
        ///function toString(){
        ///
        ///}
        ///
        ///}
        /////coment
        ///do{
        ///	$a=$a+$a;
        ///	echo &quot;cycle&quot;;
        ///	do
        ///	{
        ///		$a=$a*$a;
        ///		echo &quot;inner cycle&quot;;
        ///	}while(&quot;true&quot;==&quot;true&quot;);
        ///	$a=8;
        ///	echo &quot;cycle&quot;;
        ///}while(&quot;true&quot;==&quot;true&quot;);
        ///echo &quot;end&quot;;
        ///
        ///
        ///?&gt;.
        /// </summary>
        public static string Input2 {
            get {
                return ResourceManager.GetString("Input2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Input.
        /// </summary>
        public static string InputCustomDescription {
            get {
                return ResourceManager.GetString("InputCustomDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string InputType {
            get {
                return ResourceManager.GetString("InputType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:### ### ##0}.
        /// </summary>
        public static string IntegerFormat {
            get {
                return ResourceManager.GetString("IntegerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ///  mysql_connect(&quot;localhost&quot;, &quot;root&quot;) or die(&quot;Neda sa pripojit k databaze: &quot; . mysql_error());
        ///      mysql_select_db(&quot;metalcup&quot;) or die (&quot;Neda sa pracovat s databazov : &quot; . mysql_error());
        ///      mysql_query(&quot;set names utf8&quot;);
        ///$l=mysql_query(&quot;select * from admin&quot;)or die(mysql_error());
        ///$zaznam=mysql_fetch_array($l);
        ///$zostava=$_POST[&quot;Zostava&quot;];
        ///$lw=$_POST[&quot;LW&quot;];
        ///$rw=$_POST[&quot;RW&quot;];
        ///$c=$_POST[&quot;C&quot;];
        ///$ld=$_POST[&quot;LD&quot;];
        ///$rd=$_POST[&quot;RD&quot;];
        ///$g=$_POST[&quot;G&quot;];
        ///$formacie=&quot;&lt;table width=\&quot;700\&quot;&gt;&lt;th align=\&quot;c [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MetalcupStatis {
            get {
                return ResourceManager.GetString("MetalcupStatis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metalcup statis.
        /// </summary>
        public static string MetalcupStatisDescription {
            get {
                return ResourceManager.GetString("MetalcupStatisDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metrics Results.
        /// </summary>
        public static string MetricsResults {
            get {
                return ResourceManager.GetString("MetricsResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Warnings.
        /// </summary>
        public static string OtherWarnings {
            get {
                return ResourceManager.GetString("OtherWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Php Code.
        /// </summary>
        public static string PhpCode {
            get {
                return ResourceManager.GetString("PhpCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Metrics.
        /// </summary>
        public static string QuantityMetrics {
            get {
                return ResourceManager.GetString("QuantityMetrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        /// &lt;head&gt;
        ///  &lt;title&gt;PHP Test&lt;/title&gt;
        /// &lt;/head&gt;
        /// &lt;body style=&quot;font:14px Courier New&quot;&gt;
        /// &lt;?
        /// 
        ///    $vratit=&quot;&quot;;
        ///    for ($i=1;$i&lt;=12;$i++){
        ///      $nah=rand(0,62);
        ///      switch($nah){
        ///        case 10: $znak=0; break;
        ///        case 11: $znak=&apos;a&apos;; break; case 12: $znak=&apos;b&apos;; break; case 13: $znak=&apos;c&apos;; break;
        ///        case 14: $znak=&apos;d&apos;; break; case 15: $znak=&apos;e&apos;; break; case 16: $znak=&apos;f&apos;; break;
        ///        case 17: $znak=&apos;g&apos;; break; case 18: $znak=&apos;h&apos;; break; case 19: $znak=&apos;i&apos;; break;
        ///        case 20: [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Randomize {
            get {
                return ResourceManager.GetString("Randomize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize.
        /// </summary>
        public static string RandomizeDescription {
            get {
                return ResourceManager.GetString("RandomizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating Metrics.
        /// </summary>
        public static string RatingMetrics {
            get {
                return ResourceManager.GetString("RatingMetrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification results.
        /// </summary>
        public static string ResultTitle {
            get {
                return ResourceManager.GetString("ResultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run metrics indicating construct presence.
        /// </summary>
        public static string RunIndicatorMetrics {
            get {
                return ResourceManager.GetString("RunIndicatorMetrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run metrics measuring quantity of constructs in the code.
        /// </summary>
        public static string RunQuantityMetrics {
            get {
                return ResourceManager.GetString("RunQuantityMetrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run metrics rating the code.
        /// </summary>
        public static string RunRatingMetrics {
            get {
                return ResourceManager.GetString("RunRatingMetrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run verification.
        /// </summary>
        public static string RunVerification {
            get {
                return ResourceManager.GetString("RunVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Warnings.
        /// </summary>
        public static string SecurityWarnings {
            get {
                return ResourceManager.GetString("SecurityWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple example.
        /// </summary>
        public static string SimpleExample {
            get {
                return ResourceManager.GetString("SimpleExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?
        ///class human {
        ///public $gender;
        ///
        ///public function __construct($gender)
        ///{
        ///$this-&gt;gender = $gender;
        ///
        ///echo self::get_gender();
        ///}
        ///
        ///public function get_gender()
        ///{
        ///return $this-&gt;gender;
        ///}
        ///}
        ///
        ///class person extends human {
        ///public $name;
        ///public $surname;
        ///
        ///public function set_name($name)
        ///{
        ///$this-&gt;name = $name;
        ///}
        ///
        ///public function set_surname($surname)
        ///{
        ///$this-&gt;surname = $surname;
        ///}
        ///
        ///public  function get_name()
        ///{
        ///return $this-&gt;name;
        ///}
        ///
        ///public  function get_surname()
        ///{
        ///return $this-&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SimpleObject {
            get {
                return ResourceManager.GetString("SimpleObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple object.
        /// </summary>
        public static string SimpleObjectDescription {
            get {
                return ResourceManager.GetString("SimpleObjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifications Results.
        /// </summary>
        public static string VerificationResults {
            get {
                return ResourceManager.GetString("VerificationResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string Verify {
            get {
                return ResourceManager.GetString("Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnings.
        /// </summary>
        public static string Warnings {
            get {
                return ResourceManager.GetString("Warnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
