//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weverca.Analysis.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Weverca.Analysis.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;ISO-8859-1&quot; ?&gt;
        ///&lt;classes&gt;
        ///  &lt;class name=&quot;stdClass&quot; isFinal=&quot;false&quot;&gt;
        ///    &lt;field name=&quot;scalar&quot; type=&quot;mixed&quot; visibility=&quot;public&quot; isStatic=&quot;false&quot; isConst=&quot;false&quot; /&gt;
        ///  &lt;/class&gt;
        ///  &lt;class name=&quot;AMQPChannel&quot; isFinal=&quot;false&quot;&gt;
        ///    &lt;method static=&quot;false&quot; final=&quot;false&quot; visibility=&quot;public&quot; name=&quot;commitTransaction&quot; returnType=&quot;void&quot;/&gt;
        ///    &lt;method static=&quot;false&quot; final=&quot;false&quot; visibility=&quot;public&quot; name=&quot;__construct&quot; returnType=&quot;none&quot;&gt;
        ///      &lt;arg type=&quot;AMQPConnection&quot; optional=&quot;false&quot; byReferenc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string php_classes {
            get {
                return ResourceManager.GetString("php_classes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;ISO-8859-1&quot; ?&gt;
        ///&lt;constants&gt;&lt;constant name=&quot;E_ERROR&quot; value=&quot;1&quot; &gt;&lt;type name=&quot;integer&quot; /&gt;&lt;/constant&gt;
        ///&lt;constant name=&quot;E_DEPRECATED&quot; value=&quot;8192&quot; &gt;&lt;type name=&quot;integer&quot; /&gt;&lt;/constant&gt;
        ///&lt;constant name=&quot;E_RECOVERABLE_ERROR&quot; value=&quot;4096&quot; &gt;&lt;type name=&quot;integer&quot; /&gt;&lt;/constant&gt;
        ///&lt;constant name=&quot;E_WARNING&quot; value=&quot;2&quot; &gt;&lt;type name=&quot;integer&quot; /&gt;&lt;/constant&gt;
        ///&lt;constant name=&quot;E_PARSE&quot; value=&quot;4&quot; &gt;&lt;type name=&quot;integer&quot; /&gt;&lt;/constant&gt;
        ///&lt;constant name=&quot;E_NOTICE&quot; value=&quot;8&quot; &gt;&lt;type name=&quot;integer&quot; /&gt;&lt;/constant&gt;
        ///&lt;con [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string php_constants {
            get {
                return ResourceManager.GetString("php_constants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;ISO-8859-1&quot; ?&gt;
        ///&lt;functions&gt;
        ///&lt;function name=&quot;abs&quot; returnType=&quot;number&quot;&gt;
        ///&lt;arg type=&quot;mixed&quot; optional=&quot;false&quot; byReference=&quot;false&quot; dots=&quot;false&quot;  /&gt;
        ///&lt;/function&gt;
        ///&lt;function name=&quot;acos&quot; returnType=&quot;float&quot;&gt;
        ///&lt;arg type=&quot;float&quot; optional=&quot;false&quot; byReference=&quot;false&quot; dots=&quot;false&quot;  /&gt;
        ///&lt;/function&gt;
        ///&lt;function name=&quot;acosh&quot; returnType=&quot;float&quot;&gt;
        ///&lt;arg type=&quot;float&quot; optional=&quot;false&quot; byReference=&quot;false&quot; dots=&quot;false&quot;  /&gt;
        ///&lt;/function&gt;
        ///&lt;function name=&quot;addcslashes&quot; returnType=&quot;string&quot;&gt;
        ///&lt;arg type=&quot;str [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string php_functions {
            get {
                return ResourceManager.GetString("php_functions", resourceCulture);
            }
        }
    }
}
